/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package partegrafica;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author carlos
 */
public class ParteGrafica extends javax.swing.JFrame {
   
    ImagenFondo ejemplo2 = new ImagenFondo();
    
 
    /**
     * Creates new form ParteGrafica
     */
    public ParteGrafica() {
         this.setContentPane(ejemplo2);
     
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new ImagenFondo();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablas = new javax.swing.JTextArea();
        consulta1 = new javax.swing.JCheckBox();
        consulta2 = new javax.swing.JCheckBox();
        consulta3 = new javax.swing.JCheckBox();
        fconsultar = new javax.swing.JButton();
        titul = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        tablas.setColumns(20);
        tablas.setRows(5);
        jScrollPane1.setViewportView(tablas);

        consulta1.setBackground(new java.awt.Color(51, 0, 51));
        consulta1.setFont(new java.awt.Font("Liberation Serif", 3, 15)); // NOI18N
        consulta1.setForeground(new java.awt.Color(255, 255, 255));
        consulta1.setText("Consulta 1");
        consulta1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta1ActionPerformed(evt);
            }
        });

        consulta2.setBackground(new java.awt.Color(51, 0, 51));
        consulta2.setFont(new java.awt.Font("Liberation Serif", 3, 15)); // NOI18N
        consulta2.setForeground(new java.awt.Color(255, 255, 255));
        consulta2.setText("Consulta 2");
        consulta2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        consulta3.setBackground(new java.awt.Color(51, 0, 51));
        consulta3.setFont(new java.awt.Font("Liberation Serif", 3, 15)); // NOI18N
        consulta3.setForeground(new java.awt.Color(255, 255, 255));
        consulta3.setText("Consulta 3");
        consulta3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fconsultar.setBackground(new java.awt.Color(102, 51, 0));
        fconsultar.setFont(new java.awt.Font("Liberation Serif", 3, 15)); // NOI18N
        fconsultar.setForeground(new java.awt.Color(255, 255, 255));
        fconsultar.setText("CONSULTAR");
        fconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fconsultarActionPerformed(evt);
            }
        });

        titul.setBackground(new java.awt.Color(204, 102, 0));
        titul.setFont(new java.awt.Font("Liberation Serif", 3, 15)); // NOI18N
        titul.setForeground(new java.awt.Color(255, 255, 255));
        titul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titul.setText("RETO 5");

        limpiar.setBackground(new java.awt.Color(51, 0, 0));
        limpiar.setFont(new java.awt.Font("Liberation Serif", 3, 15)); // NOI18N
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("Limpiar");
        limpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Liberation Serif", 3, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fconsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(consulta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiar)
                    .addComponent(jButton1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(titul, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(fconsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consulta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fconsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fconsultarActionPerformed

    private void consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consulta1ActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ParteGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ParteGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ParteGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ParteGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParteGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox consulta1;
    private javax.swing.JCheckBox consulta2;
    private javax.swing.JCheckBox consulta3;
    private javax.swing.JButton fconsultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextArea tablas;
    private javax.swing.JLabel titul;
    // End of variables declaration//GEN-END:variables

    //TODO = Parte de las gráfica del reto
    
       class graficajava extends JPanel{
            
       
       private Image imagen2;
       @Override
       public void paint (Graphics g){
           
           imagen2 = new ImageIcon(getClass().getResource("java.png")).getImage();
           
           g.drawImage(imagen2, 0, 0, getWidth(), getHeight(), this);
           setOpaque(false);
           super.paint(g);
           
           
           
       }
       
   }      
 
  class ImagenFondo extends JPanel{
       
            @Override
            
            public void paint(Graphics g){
                ImageIcon imagen = new ImageIcon(getClass().getResource("imagen2.jpg"));
                g.drawImage(imagen.getImage(), 0, 0, getWidth(), getHeight(), this);
                setOpaque(false);
                super.paint(g);
            }
   }   
       
     
}
